# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cosincla <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/03 15:10:18 by cosincla          #+#    #+#              #
#    Updated: 2019/06/03 15:17:10 by cosincla         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone
FILE = megaphone.cpp

all: $(NAME)

$(NAME): 
	@clang++ -o $(NAME) $(FILE)

clean:
	@/bin/rm -rf $(NAME)

re: clean all
